<a href="https://colab.research.google.com/github/SonyFebri/Machine-Learning/blob/main/ML1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
def norm_data(data):
    """
    Melakukan normalisasi data.

    Parameters:
        data (list): Data yang akan dinormalisasi.

    Returns:
        list: Data hasil normalisasi.
    """
    data_max = max(data)
    data_min = min(data)
    data_len = len(data)
    for i in range(data_len):
        data[i] = (data[i] - data_min) / (data_max - data_min)
    return data

# Contoh Penggunaan
data = [10, 11, 12, 14, 16]
n_data = norm_data(data)  # melakukan normalisasi
print(n_data)


[0.0, 0.16666666666666666, 0.3333333333333333, 0.6666666666666666, 1.0]


In [4]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

np.set_printoptions(precision=6)  # Bulatkan ke 4 angka di belakang koma
np.set_printoptions(suppress=True)  # Hilangkan notasi eksponensial (e)

# Membentuk data sebagai n-dimensional array
data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003]
]

# Ubah ke bentuk numpy n-dimensional array
data = np.asarray(data)
print('Data Asli')
print(data)

# Mendefinisikan objek MinMaxScaler
scaler = MinMaxScaler()

# Transformasikan data
scaled = scaler.fit_transform(data)

print('Data Normalisasi')
print(scaled)


Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Normalisasi
[[1.       0.      ]
 [0.285714 1.      ]
 [0.       0.058116]]


In [7]:
import numpy as np
from sklearn.preprocessing import StandardScaler

np.set_printoptions(precision=6)  # Bulatkan ke 4 angka di belakang koma
np.set_printoptions(suppress=True)  # Hilangkan notasi eksponensial (e)

# Membentuk data sebagai n-dimensional array
data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003]
]

# Ubah ke bentuk numpy n-dimensional array
data = np.asarray(data)
print('Data Asli')
print(data)

# Mendefinisikan objek MinMaxScaler
scaler = StandardScaler()

# Transformasikan data
scaled = scaler.fit_transform(data)

print('Data Standarisasi')
print(scaled)


Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Standarisasi
[[ 1.358732 -0.76956 ]
 [-0.339683  1.412317]
 [-1.019049 -0.642757]]


In [8]:
from sklearn.preprocessing import OrdinalEncoder

# Inisiasi objek Ordinal Encoder
oe = OrdinalEncoder()

# Definisikan data dalam bentuk 2D
data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang']
]

# Transformasi menggunakan Ordinal Encoder
transform_oe = oe.fit_transform(data)

print('Data Asli')
print(data)

print('Data Transformasi Ordinal Encoder')
print(transform_oe)


Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi Ordinal Encoder
[[2.]
 [0.]
 [1.]
 [3.]]


In [11]:
from sklearn.preprocessing import OneHotEncoder

# Inisiasi objek Ordinal Encoder
ohe = OneHotEncoder()

# Definisikan data dalam bentuk 2D
data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang']
]

# Transformasi menggunakan Ordinal Encoder
transform_ohe = ohe.fit_transform(data)

print('Data Asli')
print(data)

print('Data Transformasi One-Hot Encoding')
print(transform_ohe.toarray())


Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi One-Hot Encoding
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [13]:
from sklearn.preprocessing import OneHotEncoder

# Inisiasi objek Ordinal Encoder
de = OneHotEncoder(drop='first')

# Definisikan data dalam bentuk 2D
data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang']
]

# Transformasi menggunakan Ordinal Encoder
transform_de = de.fit_transform(data)

print('Data Asli')
print(data)

print('Data Transformasi One-Hot Encoding')
print(transform_de.toarray())


Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi One-Hot Encoding
[[0. 1. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


Studi Kasus

In [16]:
corpus = [
  'the house had a tiny little mouse', 'the cat saw the mouse',
  'the mouse ran away from the house',
  'the cat finally ate the mouse',
  'the end of the mouse story'
]

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Inisiasi objek TfidfVectorizer dengan menghilangkan stop words bahasa Inggris
vect = TfidfVectorizer(stop_words='english')

# Pembobotan TF-IDF
resp = vect.fit_transform(corpus)

# Cetak hasil TF-IDF
print('TF-IDF')
print(resp)

#hasil token
print('Token')
print(vect.get_feature_names_out())

TF-IDF
  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811
Token
['ate' 'away' 'cat' 'end' 'finally' 'house' 'little' 'mouse' 'ran' 'saw'
 'story' 'tiny']


In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Membaca isi file corpus.txt
with open('corpus.txt', 'r') as file:
    corpus = file.readlines()

# Inisiasi objek TfidfVectorizer dengan menghilangkan stop words bahasa Inggris
hasil = TfidfVectorizer(stop_words='english')

# Pembobotan TF-IDF menggunakan teks dari file corpus.txt
resp = hasil.fit_transform(corpus)

# Cetak hasil
print('TF-IDF:')
print(resp.toarray())

# Menampilkan fitur (kata) yang diekstrak
print('Features:')
print(hasil.get_feature_names_out())

TF-IDF:
[[0.       0.       0.       0.       0.       0.475575 0.589463 0.280882
  0.       0.       0.       0.589463]
 [0.       0.       0.588732 0.       0.       0.       0.       0.347715
  0.       0.729718 0.       0.      ]
 [0.       0.589463 0.       0.       0.       0.475575 0.       0.280882
  0.589463 0.       0.       0.      ]
 [0.589463 0.       0.475575 0.       0.589463 0.       0.       0.280882
  0.       0.       0.       0.      ]
 [0.       0.       0.       0.670092 0.       0.       0.       0.319302
  0.       0.       0.670092 0.      ]]
Features:
['ate' 'away' 'cat' 'end' 'finally' 'house' 'little' 'mouse' 'ran' 'saw'
 'story' 'tiny']
